# Generated by Django 3.0.3 on 2020-02-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='current_room',
            field=models.IntegerField(default=None),
        ),
    ]
