# Generated by Django 3.0.3 on 2020-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_monster_current_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='current_room',
            field=models.IntegerField(default=0),
        ),
    ]
