# Generated by Django 3.0.3 on 2020-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_remove_monster_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='monster',
            field=models.IntegerField(default=-1),
        ),
    ]
