# Generated by Django 3.0.3 on 2020-02-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0010_remove_room_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='monsters',
            field=models.IntegerField(default=0),
        ),
    ]
