# Generated by Django 3.0.3 on 2020-02-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0011_room_monsters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='current_room',
        ),
        migrations.AddField(
            model_name='monster',
            name='currentRoom',
            field=models.IntegerField(default=0),
        ),
    ]
