# Generated by Django 3.0.3 on 2020-02-05 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0012_auto_20200205_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='currentRoom',
        ),
        migrations.AddField(
            model_name='monster',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
