# Generated by Django 3.0.3 on 2020-02-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0013_auto_20200205_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='uuid',
        ),
        migrations.AddField(
            model_name='monster',
            name='currentRoom',
            field=models.IntegerField(default=0),
        ),
    ]
