# Generated by Django 3.0.3 on 2020-02-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0014_auto_20200205_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.IntegerField(default=-1),
        ),
    ]
