# Generated by Django 3.0.3 on 2020-02-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0015_auto_20200205_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
